export const LOAD_DATA = 'LOAD_DATA';
export const CHANGE_DEPOSIT_TYPE = 'CHANGE_DEPOSIT_TYPE';
export const CHANGE_MONTH_VALUE = 'CHANGE_MONTH_VALUE';
export const CHANGE_SUM_VALUE = 'CHANGE_SUM_VALUE';
